version: '3.3'

services:
    redis_master:
        image: redis:4.0.14-alpine
        networks:
          redis4:
            ipv4_address: 172.22.0.5
        command: redis-server --requirepass abc --masterauth abc

    redis_slave:
        image: redis:4.0.14-alpine
        networks:
          redis4:
            ipv4_address: 172.22.0.10
        command: redis-server --requirepass abc --masterauth abc --slaveof redis_master 6379
        depends_on:
            - redis_master

    sentinel1:        
        image: pgeraghty/redis-sentinel:4.0
        networks:
          redis4:
            ipv4_address: 172.22.0.15
        environment:
            - MASTER_NAME=the-master
            - QUORUM=1
            - MASTER=redis_master
            - DOWN_AFTER=5000
            - FAILOVER_TIMEOUT=60000
            - AUTH_PASS=abc
        depends_on:
            - redis_master
    
    sentinel2:        
        image: pgeraghty/redis-sentinel:4.0
        networks:
          redis4:
            ipv4_address: 172.22.0.20
        environment:
            - MASTER_NAME=the-master
            - QUORUM=1
            - MASTER=redis_master
            - DOWN_AFTER=5000
            - FAILOVER_TIMEOUT=60000
            - AUTH_PASS=abc
        depends_on:
            - redis_master

networks:
  redis4:
    ipam:
      config:
        - subnet: 172.22.0.0/24
